title: Services
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          type: markdown
          display: Content
          localizable: true
      -
        handle: external_link
        field:
          display: 'External Link'
          type: link
          icon: link
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          validate:
            - required
      -
        handle: category
        field:
          max_items: 1
          mode: select
          taxonomies:
            - service_categories
          display: Category
          type: terms
          icon: taxonomy
          listable: hidden
      -
        handle: service_category
        field:
          max_items: 1
          mode: select
          collections:
            - service_categories
          display: 'Service Category'
          type: entries
          icon: entries
          listable: hidden
