title: 'All Hospitals'
category: hospitals-and-surgery-centers
service_category: 265a8449-098b-49e2-b9a5-c5a95170ea6c
updated_by: a034f527-2110-44df-82f7-baa1cb1b5355
updated_at: 1621886787
blueprint: services
active: true
