title: Attorney
category: legal-services
service_category: d7d07038-bcf8-4e4e-93bf-094bdfbb1553
active: true
updated_by: 87a74d1c-1760-42c5-afc1-1cc59be16098
updated_at: 1710950291
blueprint: services
