title: 'Complimentary Medicine'
category: complementary-medicine
service_category: dfd044b4-17b9-416c-8b43-c327df2bafbd
active: true
updated_by: 87a74d1c-1760-42c5-afc1-1cc59be16098
updated_at: 1658930055
blueprint: services
