title: 'Food Stamps'
category: community-resources
service_category: 7e3b51e7-19df-460e-abe1-4b9782628acf
updated_by: a034f527-2110-44df-82f7-baa1cb1b5355
updated_at: 1619752117
blueprint: services
active: true
external_link: 'https://dwss.nv.gov/SNAP/Food/'
