title: 'Inpatient Psychiatric Treatment'
category: behavioral-health
service_category: d553c578-78c2-4ac3-8864-03b2050e08dc
active: true
updated_by: a034f527-2110-44df-82f7-baa1cb1b5355
updated_at: 1622819902
blueprint: services
