title: 'Legal Aid'
category: legal-services
service_category: d7d07038-bcf8-4e4e-93bf-094bdfbb1553
updated_by: a034f527-2110-44df-82f7-baa1cb1b5355
updated_at: 1622825792
blueprint: services
active: true
external_link: 'https://www.nevada211.org/legal-aid/'
