title: 'Medical Weight Loss Clinic'
category: doctors
service_category: 5c877bf9-2184-43bc-9426-b10e56ded517
active: true
updated_by: 87a74d1c-1760-42c5-afc1-1cc59be16098
updated_at: 1676577519
blueprint: services
