title: 'Molecular Laboratory'
category: imaging-and-labs
service_category: 1b3b7bd2-4839-487a-a954-6563bcad64e4
active: true
updated_by: 87a74d1c-1760-42c5-afc1-1cc59be16098
updated_at: 1661454016
blueprint: services
