title: 'Neurologic Rehabilitation'
category: hospitals-and-surgery-centers
service_category: 265a8449-098b-49e2-b9a5-c5a95170ea6c
active: true
updated_by: 87a74d1c-1760-42c5-afc1-1cc59be16098
updated_at: 1689809189
blueprint: services
