title: 'Social Services'
category: community-resources
service_category: 7e3b51e7-19df-460e-abe1-4b9782628acf
updated_by: a034f527-2110-44df-82f7-baa1cb1b5355
updated_at: 1619752147
blueprint: services
external_link: 'https://www.clarkcountynv.gov/residents/assistance_programs/index.php'
